controller_frequency: 1.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   max_vel_x: 0.2 #robot's max speed limit to 0.1 m/s
   min_vel_x: 0.02 #robot's min speed at least 0.02 m/s
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_rotation_vel: 0.05 #max rotation speed
   min_in_place_vel_theta: 0.01 
   escape_vel: -0.02
   acc_lim_x: 0.05
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 0.01

   holonomic_robot: false
   yaw_goal_tolerance: 0.5 # about ? degrees
   xy_goal_tolerance: 0.5  # 50 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.6
   gdist_scale: 1.0
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.1
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 8
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: false
